project:
  type: website
  output-dir: docs

website:
  title: "Wooyong Park"
  favicon: "photos/yonsei.jpg"
  navbar:
    logo: "photos/yonsei.jpg"
    left:
      - href: index.qmd
        text: Home
      # - favorite_books.qmd
      - href: slides.qmd
        text: Slides

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



