project:
  type: website
  output-dir: docs

website:
  title: "Wooyong Park"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - favorite_books.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



