project:
  type: website
  output-dir: "docs"  
  resources: ["ref/cv_public.pdf"]
    
website:
  title: "Wooyong Park"
  favicon: "photos/yonsei.jpg"
  navbar:
    logo: "photos/yonsei.png"
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      # - favorite_books.qmd
      - href: posts/index.qmd
        text: Posts
  search: 
    type: textbox
      

format:
  html:
    theme: 
      light: lux
      dark: darkly
    css: styles.css
    toc: false



