---
title: "Slides and Materials"
---

### Applied Microeconomics Reading Group, Yonsei University
- [Introduction to Nationwide Panel Datasets(PSID, KLIPS, CNEF)](https://www.dropbox.com/scl/fi/3jtoo2se7ug6o0io5rugj/nationwide-panel-data-sets_public.pdf?rlkey=jhjsl6cvljn8qif9021ubgd6m&dl=0)
- [Social Media and Mental Health(Braghieri et al., 2022)](https://www.dropbox.com/scl/fi/jxzuo72gy9ccq333rmwol/Social_Media_and_Mental_Health_public.pdf?rlkey=4jy4i8t7on3jktzndifx2ovwt&dl=0)


### Applied Economic Methods Study Group, Yonsei University
I started out this study group in January(2024) with students in the Economics department who aim for attaining PhD in Applied Economics. We are planning to have this study group every vacation between semesters, and pass on the materials and resources to future students as well. I gave presentations on topics such as ***clustering standard errors*** and ***staggered difference-in-differences***.
<br>

- [Cluster Robust Standard Errors](slides/Cluster_SE.html)
- [Staggered Difference-in-Differences I](https://www.dropbox.com/scl/fi/rrg7puid9k5btqk6cp7n4/sdid1_public.pdf?rlkey=pti5il9zfrzz0xkb4snbbfxa5&dl=0)
- [Staggered Difference-in-Differences II(R)](https://www.dropbox.com/scl/fi/93khcx8lsoveeqd7mz2hc/sdid2-R-_public.pdf?rlkey=p2ja1mykqiah5u0paix7xipm0&dl=0)
- [Staggered Difference-in-Differences II(Stata)](https://www.dropbox.com/scl/fi/b3eu1bkmudg3lurmike4p/sdid2-STATA-_public.pdf?rlkey=aa5pxtc2715i4dwfdq24bntiw&dl=0)
<br>


### Junior Scholar Club, Yonsei University
- [Social Connectedness and Information Markets(Kranton and McAdams, 2024)](https://www.dropbox.com/scl/fi/yggwknxu3cevc58k9c22k/JSC_Weekly_24_1-_.pdf?rlkey=9ov5j2rzfpxbaizjxdc3cyy7k&dl=0)

### Elsewhere
- [Data Summary: KLIPS(Korean Labor Institute Panel Study)(KOR)](https://www.dropbox.com/scl/fi/sjom2vvamipv6i4009vvg/klips_wypark_public.pdf?rlkey=ztmymtq4jdu2ojlrb3dp1nfdq&dl=0)
- [Data Summary: PSID(Panel Study of Income Dynamics)](https://www.dropbox.com/scl/fi/8ao0yx4twyes45kferww6/psid_wypark_public.pdf?rlkey=hyvq9li3hcyjycsgsujk1mzit&dl=0)
- [Economics for Highschool Students(KOR)](https://www.dropbox.com/scl/fi/2qx9qujk6mgh6nb62cv1h/_-_-_-_.pdf?rlkey=pi4xf5rwol1k7dmt6mai5s68v&dl=0) <br> &rarr; Here I visited my alma mater and introduced DiD and IV to highschool students.
